name: Test

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          registry-url: 'https://registry.yarnpkg.com'
          cache: 'yarn'

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'yarn'

      - name: Fetch dependencies
        run: |
          yarn
      - name: Test typescript
        run: |
          yarn test
